java:
  # aadIdentityName needs to be unset as it's not used in preview env yet
  aadIdentityName:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    SWAGGER_ENABLED: true
