package uk.gov.hmcts.reform.finrem.notifications.domain;

public enum EmailTemplateNames {
    FR_HWF_SUCCESSFUL,
    FR_ASSIGNED_TO_JUDGE,
    FR_CONSENT_ORDER_MADE,
    FR_CONSENT_ORDER_NOT_APPROVED,
    FR_CONSENT_ORDER_AVAILABLE,
    FR_CONSENT_ORDER_AVAILABLE_CTSC,
    FR_CONTESTED_HWF_SUCCESSFUL,
    FR_CONTESTED_APPLICATION_ISSUED,
    FR_CONTESTED_PREPARE_FOR_HEARING,
    FR_CONTESTED_PREPARE_FOR_HEARING_ORDER_SENT,
    FR_CONTEST_ORDER_APPROVED,
    FR_CONTESTED_DRAFT_ORDER,
    FR_CONTEST_ORDER_NOT_APPROVED,
    FR_CONTESTED_CONSENT_ORDER_APPROVED,
    FR_CONTESTED_CONSENT_ORDER_NOT_APPROVED,
    FR_CONTESTED_GENERAL_ORDER_CONSENT,
    FR_CONTESTED_GENERAL_APPLICATION_REFER_TO_JUDGE,
    FR_CONTESTED_GENERAL_APPLICATION_OUTCOME
}
