package uk.gov.hmcts.reform.finrem.notifications.domain;

public enum EmailTemplateNames {
    FR_HWF_SUCCESSFUL,
    FR_ASSIGNED_TO_JUDGE,
    FR_CONSENT_ORDER_MADE,
    FR_CONSENT_ORDER_NOT_APPROVED,
    FR_CONSENT_ORDER_AVAILABLE,
    FR_CONTESTED_HWF_SUCCESSFUL,
    FR_CONTESTED_APPLICATION_ISSUED,
    FR_CONTESTED_PREPARE_FOR_HEARING,
}
